# Generated by Django 4.1.7 on 2023-03-28 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=400)),
                ("slug", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="media")),
                ("price", models.IntegerField()),
                ("discounted_price", models.IntegerField(default=0)),
                (
                    "stock",
                    models.CharField(
                        choices=[("in", "In Stock"), ("out", "Out of Stock")],
                        max_length=20,
                    ),
                ),
                (
                    "labels",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hot", "hot"),
                            ("sale", "sale"),
                            ("new", "new"),
                            ("", "default"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("specification", models.TextField(blank=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.category"
                    ),
                ),
            ],
        ),
    ]
