# Generated by Django 4.1.7 on 2023-03-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_slider"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="media")),
                ("description", models.TextField(blank=True)),
                ("rank", models.IntegerField(unique=True)),
            ],
        ),
    ]
